# Local Path StorageClass for local Kubernetes clusters (minikube, k3d, kind)
# This is a fallback option if your cluster doesn't have a default StorageClass
#
# Usage:
#   kubectl apply -f storageclass-local-path.yaml
#   kubectl patch storageclass local-path -p '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
#
# Note: This requires the local-path-provisioner to be installed in your cluster
# For minikube: minikube addons enable default-storageclass
# For k3d: Usually comes pre-installed
# For kind: Install local-path-provisioner separately

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

